import Head from "next/head";

export function Headline() {
  return (
    <Head>
      <title>My Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Caveat&display=swap"
        rel="stylesheet"
      />

      <link
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap"
        rel="stylesheet"
      ></link>

      <link
        href="https://fonts.googleapis.com/css2?family=Carter+One&display=swap"
        rel="stylesheet"
      />
      <link rel="icon" href="#" />
    </Head>
  );
}
