import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

import { Header } from "../components/header";
import { Sideleft } from "../components/sideleft";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"/> 
        <link rel="icon" href="/s-logo.svg" />
      </Head>

      <Sideleft />

      <div className={styles.sidebarRight}> 
        <h3>SIDEBAR RIGHT</h3>
      </div>

      <Header />

      <section className={styles.about}>
        <h2>SECTION 1</h2> 
      </section>

      <section className={styles.skills}>
      <h2>SECTION 2</h2> 
      </section>

      <section className={styles.works}>
      <h2>SECTION 3</h2> 
      </section>

      <section className={styles.contact}>
      <h2>SECTION 4</h2> 
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
