import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.sidebarLeft}> 
        <h3>SIDEBAR LEFT</h3>
      </div>

      <div className={styles.sidebarRight}> 
        <h3>SIDEBAR RIGHT</h3>
      </div>

      <header className={styles.header}>
        <h1>HEADER</h1>
      </header>

      <section className={styles.about}>
        <h2>SECTION 1</h2> 
      </section>

      <section className={styles.skills}>
      <h2>SECTION 2</h2> 
      </section>

      <section className={styles.works}>
      <h2>SECTION 3</h2> 
      </section>

      <section className={styles.contact}>
      <h2>SECTION 4</h2> 
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
